# Generated by Django 3.1.1 on 2020-09-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingModel',
            new_name='ShippingAddres',
        ),
    ]
